name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: thatgeekyweeb
          template: repository
          repositories_forks: yes
          config_animated: yes
          config_twemoji: yes
          config_timezone: Canada/Eastern
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 8
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0.2%
          plugin_followup: yes
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
