name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: thatgeekyweeb
          setup_community_templates: thatgeekyweeb/metrics@master:terminal
          repositories_forks: yes
          config_timezone: Canada/Eastern
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_threshold: 0.2%
